image: node:18

stages:
  - build
  - deploy

before_script:
  - npm install 

build:
  stage: build
  script:
    - npm run build -- --output-path=dist/world-map --configuration=production 
  artifacts:
    paths:
      - dist/world-map  
    

pages:
  stage: deploy
  script:
    - mkdir -p public                     
    - mv dist/world-map/* public/ 
  artifacts:
    paths:
      - public  
  only:
    - workingbranch

