pages:
  image: node:18 
  script:
    - npm install  
    - npm run build -- --output-path=dist/world-map --configuration=production  
  artifacts:
    paths:
      - dist/world-map  
  only:
    - workingbranch
