image: node:18

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm install                 
    - npm run build -- --output-path=public --configuration=production  
  artifacts:
    paths:
      - public            
pages:
  stage: deploy
  script:
    - echo "Deploying to GitLab Pages"
  artifacts:
    paths:
      - public
  only:
    - workingbranch          

      