image: node:18

cache:
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm install                           
    - npm run build -- --configuration=production  
  artifacts:
    paths:
      - public
  only:
    - workingbranch  
