image: node:18

stages:
  - build
  - deploy

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build -- --output-path=dist/world-map --configuration=production
  artifacts:
    paths:
      - dist/world-map

pages:
  stage: deploy
  script:
    - mkdir -p public
    - cp -r dist/world-map/browser/* public/
    - echo '<!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Redirecting...</title>
        <script>
          // Redirect to index.html for SPA fallback
          window.location.href = "/";
        </script>
      </head>
      <body>
        <p>Redirecting...</p>
      </body>
      </html>' > public/404.html
  artifacts:
    paths:
      - public
  only:
    - workingbranch
