image: node:18

stages:
  - build
  - deploy

before_script:
  - npm install

build:
  stage: build
  script:
    - npm run build -- --output-path=public --configuration=production
  artifacts:
    paths:
      - public

pages:
  stage: deploy
  script:
    - mv public/ ../public
  artifacts:
    paths:
      - public
  only:
    - main
    - workingbranch